name: arp-to-hosts

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

jobs:
  make:
    name: make
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - run: make
      - run: make coverage
