name: arp-to-hosts

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches:
      - master
  push:
    branches:
      - master

env:
  COVERALLS_REPO_TOKEN: ${{ secrets.COVERALLS_REPO_TOKEN }}

jobs:
  make:
    name: make
    runs-on: ubuntu-18.04
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.7.9
      - uses: actions/cache@v2
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-
          restore-keys: ${{ runner.os }}-pip-
      - run: pip install -r requirements.txt

      # formatting, type safety, linting, tests, test coverage
      - run: make ci

      # submit results
      - run: coveralls
